server:
  port: 521
  servlet:
    context-path: /api
spring:
  main:
    banner-mode: off
    allow-bean-definition-overriding: true
  application:
    name: wish-list
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://43.138.151.235:3306/wish_list?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
    url: jdbc:mysql://10.211.55.3:3306/wish_list?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: "2762581@com"
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl
  global-config:
    banner: false
